# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Getting Started
              item_url: '/getting-started/'
            - item_name: Infrastructure
              item_url: '/infrastructure'
    footer:
        content:
            logo:
                text: SpotiPay
                image:
            copyright: Copyright &copy; 2020. - SpotiPay <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/SpotiPay'            
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
